apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::717224861897:role/eksctl-eksctl-simple-jwt-api-node-NodeInstanceRole-1LVLOLSFRPJJW
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T09:38:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2280"
  uid: d6ab6221-cd24-42f5-ac8a-fea5a697cbe1
